#!/usr/bin/env node
/**
 * Build script: generates items-data.js from a VNC Infor item master XLSX export.
 *
 * Usage:
 *   node scripts/build-items.mjs <path-to-xlsx>
 *
 * Expected XLSX columns (case-insensitive header match):
 *   Item, Item Description, Item Description3, UNSPSC Description,
 *   Mfr Division Name, Mfr Item
 *
 * Output: items-data.js in repo root — classic script defining
 *   CATALOG_META  { campus, asOf, count }
 *   ITEM_CATALOG  [ { item, desc, desc3, unspsc, mfr, mfrItem }, ... ]
 *
 * Filename date parsing: looks for pattern YY_MM_DD anywhere in the filename
 * (e.g. "26_07_07") and interprets as 20YY-MM-DD. Falls back to today if absent.
 */

import { writeFileSync } from "fs";
import { basename, resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

// Install xlsx on demand if missing
let XLSX;
try {
  XLSX = require("xlsx");
} catch {
  console.error("The 'xlsx' package is required. Run: npm install xlsx");
  process.exit(1);
}

const [,, xlsxPath] = process.argv;
if (!xlsxPath) {
  console.error("Usage: node scripts/build-items.mjs <path-to-xlsx>");
  process.exit(1);
}

// --- Parse as-of date from filename (supports separators _ . or -) ---
const fname = basename(xlsxPath);
const dateMatch = fname.match(/(\d{2})[_.\-](\d{2})[_.\-](\d{2})/);
let asOf;
if (dateMatch) {
  const [, yy, mm, dd] = dateMatch;
  asOf = `20${yy}-${mm}-${dd}`;
} else {
  const t = new Date();
  asOf = `${t.getFullYear()}-${String(t.getMonth() + 1).padStart(2, "0")}-${String(t.getDate()).padStart(2, "0")}`;
  console.warn(`No date pattern (YY_MM_DD) found in filename; using today: ${asOf}`);
}

// --- Read workbook ---
console.log(`Reading: ${xlsxPath}`);
const workbook = XLSX.readFile(xlsxPath);
const sheetName = workbook.SheetNames[0];
const sheet = workbook.Sheets[sheetName];
const rawRows = XLSX.utils.sheet_to_json(sheet, { defval: "" });

if (!rawRows.length) {
  console.error("No rows found in sheet.");
  process.exit(1);
}

// --- Normalize headers (case-insensitive key lookup) ---
function pickField(row, candidates) {
  const keys = Object.keys(row);
  for (const candidate of candidates) {
    const hit = keys.find((k) => k.trim().toLowerCase() === candidate.toLowerCase());
    if (hit !== undefined) return String(row[hit] ?? "").trim();
  }
  return "";
}

// --- Deduplicate on Item number (keep first occurrence) ---
const seen = new Set();
const items = [];

for (const row of rawRows) {
  const item = pickField(row, ["Item"]);
  if (!item || seen.has(item)) continue;
  seen.add(item);

  items.push({
    item,
    desc:    pickField(row, ["Item Description"]),
    desc3:   pickField(row, ["Item Description3"]),
    unspsc:  pickField(row, ["UNSPSC Description"]),
    mfr:     pickField(row, ["Mfr Division Name"]),
    mfrItem: pickField(row, ["Mfr Item"]),
  });
}

console.log(`  ${rawRows.length} rows read, ${items.length} unique items after dedup`);

// --- Emit items-data.js ---
const outPath = resolve(dirname(fileURLToPath(import.meta.url)), "..", "items-data.js");

const meta = { campus: "CPMC Van Ness", asOf, count: items.length };

const lines = [
  "    // Auto-generated by scripts/build-items.mjs — do not edit by hand.",
  `    // Source: ${fname}`,
  `    // Generated: ${new Date().toISOString().slice(0, 10)}`,
  "",
  `    const CATALOG_META = ${JSON.stringify(meta, null, 2).replace(/^/gm, "    ").trim()};`,
  "",
  "    const ITEM_CATALOG = [",
  ...items.map((it, i) => {
    const comma = i < items.length - 1 ? "," : "";
    return `      ${JSON.stringify(it)}${comma}`;
  }),
  "    ];",
  "",
];

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote ${outPath}`);
console.log(`  Campus: ${meta.campus}  |  As of: ${meta.asOf}  |  Items: ${meta.count}`);
